### ISSUE TITLE
新婚快乐

### ISSUE THREAD

**Issue by chaserr** [iammapping/wedding#13]
你好，我想问一下你这个部署到服务器是需要有自己的服务器对吗？

**Comment by iammapping** [comment]
严格来说是要部署到一台外网可以访问的服务器上，不一定是要自己的😁

**Comment by chaserr** [comment]
你好，我想问一下，我的微信公共号在自动登录后总是授权失败，跳转到 reauth 页面，目测是 code 获取失败，请问该怎么解决啊
ps:我的是测试号。
@iammapping
