### ISSUE TITLE
手机端访问不显示

### ISSUE THREAD

**Issue by dchaofei** [iammapping/wedding#16]
嘿嘿，感觉很有趣，想研究一下，在微信开发工具上能显示，在手机端用微信访问打不开，请求显示如下图，谢谢。
![image](https://user-images.githubusercontent.com/29528188/36594597-c6af59e0-18d9-11e8-881c-c20b6b6bc660.png)

**Comment by iammapping** [comment]
可以设置手机网络代理调试看看

**Comment by iammapping** [comment]
有问题我再重新开启
