### ISSUE TITLE
求指导

### ISSUE THREAD

**Issue by jsvr** [iammapping/wedding#2]
mac 上跑了一下,没成功,马上结婚了,希望牛逼的楼主指点指点!

**Comment by iammapping** [comment]
@jsvr 在哪失败，失败的原因是啥？

**Comment by coolicer** [comment]
@iammapping 
我也随便跑了一下，报错：
/Project/wedding/node_modules/.4.15.2@sequelize/lib/sequelize.js:175
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');

**Comment by Brania** [comment]
Error: Dialect needs to be explicitly supplied as of v4.0.0

node -v 
8.7.0

**Comment by iammapping** [comment]
@coolicer @Brania 多谢反馈，由于是去年的项目，还没测过这么高版本的 node，当时使用 node 4.x，我晚上试试

**Comment by jsvr** [comment]
@iammapping  /Users/lixiaowan/Desktop/mr.zhang/HomeStudy/project/婚礼请柬/wedding-master/node_modules/_sequelize@4.15.2@sequelize/lib/sequelize.js:175
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0

**Comment by jsvr** [comment]
我俩 都是node 版本过高?

**Comment by iammapping** [comment]
85d20ba314c7f3f809461700627a6edf97950494 已经修复，是 Sequelize 版本太高的原因，添加了 package-lock.json，你们重新安装下，没啥问题我就关闭这个 issue 了。

**Comment by jsvr** [comment]
@iammapping  我试试

**Comment by jsvr** [comment]
@iammapping  throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
,我的还是不行

**Comment by jsvr** [comment]
verbose: Using default connection named sequelizeServer
/Users/lixiaowan/Desktop/mr.zhang/HomeStudy/project/婚礼请柬/wedding/node_modules/_sequelize@4.16.1@sequelize/lib/sequelize.js:175
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0

**Comment by iammapping** [comment]
@jsvr 麻烦再重新安装下，一些依赖包的版本不一致导致

**Comment by Brania** [comment]
@iammapping 已解决

**Comment by jsvr** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1337
  at Object.exports._errnoException (util.js:1018:11)
  at exports._exceptionWithHostPort (util.js:1041:20)
  at Server._listen2 (net.js:1258:14)
  at Server._listen2 (/Users/lixiaowan/Desktop/aaa/wedding/node_modules/_async-listener@0.6.8@async-listener/index.js:85:23)
  at listen (net.js:1294:10)
@iammapping 我怎么那么尴尬

**Comment by iammapping** [comment]
@jsvr 你这是端口被占用了，你可以`lsof -i :1337`，看看那个进程，把他杀掉，然后重新启动，或者看下 sails 怎么修改启动端口。这个不属于这个 issue 的问题，我把这个关闭了
