### ISSUE TITLE
微信端访问不存在：Not Found

### ISSUE THREAD

**Issue by BoushZhou** [iammapping/wedding#20]
**后台返回代码：报错的部分已加黑**

Requested ::  GET /
Requested ::  GET /home/wedding-master?code=001fFXta2vqpZO0Tcwwa2Y1Gta2fFXt0&state=
**verbose: Sending 404 ("Not Found") response**
Requested ::  GET /styles/weui.min.css
Requested ::  GET /styles/home.css
Requested ::  GET /styles/jquery.fullpage.min.css
Requested ::  GET /styles/slick.css
Requested ::  GET /styles/wall.css
Requested ::  GET /js/dependencies/jquery.min.js
Requested ::  GET /js/dependencies/comment.js
Requested ::  GET /js/dependencies/slick.min.js
Requested ::  GET /js/dependencies/jquery.fullpage.min.js
Requested ::  GET /js/pm.js
Requested ::  GET /js/home.js
Requested ::  GET /js/wall.js
**Requested ::  GET /styles/jquery.fullpage.min.css.map
verbose: Sending 404 ("Not Found") response**
**Requested ::  GET /js/dependencies/jquery.min.map
verbose: Sending 404 ("Not Found") response
Requested ::  GET /js/dependencies/jquery.fullpage.min.js.map
verbose: Sending 404 ("Not Found") response**

**Comment by iammapping** [comment]
上面第一个应该是你的回调地址设置有误，应该是 home/resolve。下面的是找不到压缩文件的sourceMap，可以忽略，不影响

**Comment by BoushZhou** [comment]
非常感谢，问题已经解决了。已经很好了，谢谢楼主。
**如果微信端支持 不是测试版本就好了，希望楼主能解决非认证的公众帐号问题。嘿嘿**
