### ISSUE TITLE
授权失败

### ISSUE THREAD

**Issue by liweiqiao** [iammapping/wedding#21]
在微信开发者工具中打开http://127.0.0.1:1337/home/reauth时授权失败

![image](https://user-images.githubusercontent.com/36891695/36943713-7eb784d2-1fc8-11e8-8585-0bf79d242a6d.png)

**Comment by iammapping** [comment]
清除cookie，检查数据库这些是不是好的

**Comment by liweiqiao** [comment]
还是同样的错误，数据库建立了，但没有写入数据，微信开发者打开还是授权失败

**Comment by iammapping** [comment]
那请提供下更详细的错误说明，比如你的环境信息，请求日志，有无错误堆栈等

**Comment by ColdBrando** [comment]
Requested ::  GET /home/resolve?code=061MWEbK18Jfi60GwqcK1NRsbK1MWEbG&state=
verbose: Executing (default): INSERT INTO `wx_accounts` (`accountID`,`openID`,`accessToken`,`refreshToken`,`expireIn`,`tokenTime`,`createTime`,`lastUpdateTime`) VALUES (xxxx,'xxxx,'xxx','xxx',7200,'2018-04-02 22:35:42','2018-04-02 22:35:42','2018-04-02 22:35:42') ON DUPLICATE KEY UPDATE `accountID`=VALUES(`accountID`), `openID`=VALUES(`openID`), `accessToken`=VALUES(`accessToken`), `refreshToken`=VALUES(`refreshToken`), `expireIn`=VALUES(`expireIn`), `tokenTime`=VALUES(`tokenTime`), `lastUpdateTime`=VALUES(`lastUpdateTime`);
Requested ::  GET /home/reauth
verbose: Rendering view: "reauth" (located @ "/Users/xxx/xxx/wedding/wedding/views/reauth")
verbose: • using configured layout:: layout.alert (located @ "/Users/xxx/xxx/wedding/wedding/views/layout.alert")
Requested ::  GET /styles/weui.min.css
Requested ::  GET /styles/home.css
Requested ::  GET /styles/jquery.fullpage.min.css
Requested ::  GET /styles/slick.css
Requested ::  GET /styles/wall.css
Requested ::  GET /styles/jquery.fullpage.min.css.map
verbose: Sending 404 ("Not Found") response

同样的问题，这个日志

**Comment by iammapping** [comment]
@fanOfDemo 你把这个语句直接拿到 DB 执行试试会不会报错。

**Comment by ColdBrando** [comment]
Table 'wedding.wx_accounts' doesn't exist 表没创建成功？

**Comment by iammapping** [comment]
@fanOfDemo 建表 sql 文件了解一下

**Comment by ColdBrando** [comment]
重新执行了一下，source wedding.sql; 现在好了

**Comment by ColdBrando** [comment]
感谢指导，demo跑起来了

**Comment by zengyu714** [comment]
@iammapping 下午好，我也遇到了授权失败的错误，数据表已经建立未写入数据
日志为：
```
Requested ::  GET /home/resolve?code=081q0vuK1FrZd5017gsK1TRmuK1q0vuc&state=
Requested ::  GET /home/reauth
Rendering view: "reauth" (located @ "/root/repo/happy-birthday/views/reauth")
? using configured layout:: layout.alert (located @ "/root/repo/happy-birthday/views/layout.alert")
Requested ::  GET /min/production.v1528276636903.min.css
```
错误可能在：
![image](https://user-images.githubusercontent.com/20368643/41029749-1a8e36be-69af-11e8-86d2-edf9a028bf5f.png)
请问要如何解决呢

**Comment by zengyu714** [comment]
MySQL 8.0的版本也会授权失败，5.7可以

**Comment by iammapping** [comment]
@zengyu714 之前没试过这么高版本的 MySQL，欢迎 pull request

**Comment by fcbhank** [comment]
> MySQL 8.0的版本也会授权失败，5.7可以

确实如此👍
