### ISSUE TITLE
背景音乐微信端无法自动播放

### ISSUE THREAD

**Issue by zhaorx** [iammapping/wedding#25]
BGM在手机微信端无法自动播放，需要点击音乐图标才能开始循环播放。微信开发者工具测试会报错如下
![image](https://user-images.githubusercontent.com/13824730/38139373-b56fe3d6-3461-11e8-928c-441b7852b0ea.png)

**Comment by iammapping** [comment]
好的，我晚点看下

**Comment by iammapping** [comment]
已修复，兄弟再试下@zhaorx 
对了，记得把配置的 `autoplay` 设为 `true` 才可以自动播放

**Comment by zhaorx** [comment]
ok @iammapping
