### ISSUE TITLE
问一个部署的问题，当前域名在用，微信授权只能是一个域名

### ISSUE THREAD

**Issue by dreammis** [iammapping/wedding#27]
当前的a域名在用，demo默认开启1337.而微信授权只能是一个域名额。

我尝试配置a.bb.com:1337/home/resolve，微信那边不支持1337这种带端口的回调。会报错

尝试配置另一个二级域名x，配置nginx转发本地1337端口到x的二级域名上
x.bb.com/home/resolve  结果微信只能设置一个回调。

额，不知道大家有没有什么好的办法.

**Comment by dreammis** [comment]
因为我没有服务号，使用公司的服务号，但是这个授权已经在一个域名上了.

网络上有方案可以同一个授权域名在多个域名下使用。这种的话，就需要修改作者的源码，还没着手做，我这边是后端，代码我知道在哪里，我怕搞了出来一堆坑。
所以先问问有没有好的解决方案 - -#

**Comment by dreammis** [comment]
网络上有那种微信一个授权域名到多个域名的解决方案，是需要在调用授权的时候，指定特殊的地址，用那个js或者php去处理，再转到指定的域名，返回state以及code。

这个怎么改。。。我看了下工程用的是wechat-oauth的一个三方库。
现在又不知道怎么捣鼓了...

**Comment by iammapping** [comment]
可以在 a.bb.com 加个代理页，比如让 a.bb.com/wedding_resolve_proxy 携带参数重定向到你的 a.bb.com:1337/home/resolve，在 nginx 或者 a.bb.com 的后端路由配一下

**Comment by dreammis** [comment]
已经解决了，使用网络上普遍解决一个授权域名授权多个域名的方式。我修改了node_modules的wechat-oauth库中的授权地址。改为本地的一个多方授权接口。

nginx这个代理，我研究研究，如果可行，那么比我这个简单多了，谢谢

**Comment by dreammis** [comment]
求教，抽奖这个彩蛋，不晓得怎么玩。 - -#

**Comment by dreammis** [comment]
抽奖这个页面，是签到的才会在奖池中吗。感觉这个页面，我点开始之后，好像只有一个我自己的图像。

**Comment by dreammis** [comment]
而且点击开始，停止不了，过一会儿才能停止，接着第二次打开开始，就点不了按钮了。不知道是我操作有问题还是本来就是这样。

**Comment by dreammis** [comment]
额，我试了下得签到才可以。打扰了。

**Comment by iammapping** [comment]
抽奖过一会才停是特性不是 bug 😁，营造点紧张的气氛，一点就停多尴尬，看起来像提前安排好的

**Comment by dreammis** [comment]
嗯嗯，我发现了，因为一开始就我自己点了签到，看log也没错，感觉画面不动，好像这个页面有问题似的...

明白了，作者很用心哦~

**Comment by awabuda** [comment]
你好，我自己纯前端一个，想问问，只是本地起服务可以吗；是不是必须部署

**Comment by iammapping** [comment]
@awabuda 自己玩玩可以本地跑个服务，详见 readme 中的微信调试。正式使用时，服务器、已备案的域名、已认证的服务号、新娘缺一不可

**Comment by sunnysk** [comment]
@iammapping 线上的话，是注册微信的订阅号还是服务号呢？

**Comment by iammapping** [comment]
@sunnysk 哥们看下上一条回复，**已认证的服务号**
