### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by zhangkun0625** [iammapping/wedding#34]
打开http://127.0.0.1:1337/就是Not Found,感觉都没报错啊,但是一直显示Not Found,Mac系统sails-v : 1.1.0  node-v :v8.12.0

**Comment by iammapping** [comment]
访问日志放出来看看呀

**Comment by zhangkun0625** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) 在浏览器上看到这个算吗?终端上没打印东西

**Comment by iammapping** [comment]
有没有其他什么程序占用了 1337 端口，可以 `lsof -i :1337` 看看是不是 sails 进程。

**Comment by zhangkun0625** [comment]
COMMAND  PID      USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
node    2118 lxmacmini   13u  IPv6 0x51e90346fe3eaf1      0t0  TCP *:menandmice-dns (LISTEN)
看到是这样的,被node占用了吗?打开127.0.0.1:1337小图标是一个帆船的啊,

**Comment by zhangkun0625** [comment]
大佬加下我qq帮忙指点下可以吗?
61992850

**Comment by iammapping** [comment]
参考 #35
