### ISSUE TITLE
微信公众号是订阅号是不是没法用阿

### ISSUE THREAD

**Issue by ParadeTo** [iammapping/wedding#4]

**Comment by iammapping** [comment]
是的。可以用一个测试公众号，然后扫码关注后，自动回复链接地址给关注人，打开地址访问，不过这有 100 人上限。成本稍高的做法是淘宝上找人代认证。或者你们公司有的话借来用一下，没啥影响，我就是这么干的。

**Comment by ParadeTo** [comment]
谢谢。还有个问题请教一下： 我看到HomeController 里面有个resolve 方法是用来获取微信传过来的code的，但是这个方法是在哪调用的呢，没有发现对应的routes配置呀

**Comment by iammapping** [comment]
这个我稍后在 README 中说明一下，这是微信公众号后台设置的回调地址。

**Comment by iammapping** [comment]
@ParadeTo 已在 README 中说明

**Comment by Brania** [comment]
申请的测试公众号也属于订阅号，无法做到静默授权。。楼主的测试号是怎么做到的？

**Comment by Brania** [comment]
测试号怎么设置自动回复啊？
@iammapping

**Comment by zhaorx** [comment]
为什么订阅号无法使用？

**Comment by iammapping** [comment]
@zhaorx 请参考微信公众号权限文档
