### ISSUE TITLE
关于打包部署服务器的问题

### ISSUE THREAD

**Issue by PWA2000** [iammapping/wedding#5]
首先恭喜楼主，项目很有意思。只是package.json中木有build命令，如何打包发布到阿里云服务器呢？

**Comment by iammapping** [comment]
用的 sails 框架，每次启动前会自动 build，你可以到服务器上拉代码，然后 `node app.js` 或 `sails lift` 启动，这不是一个纯静态的项目，不能打个包丢到服务器上就可以跑。如果你一定要提前打包，sails 是用的 grunt 作为构建工具，本地可以 `grunt build`，生产环境可以 `grunt buildProd`。

**Comment by iammapping** [comment]
如果有问题，我再重新打开这个 issue
